[package]
name = "hiemal"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0.149", features = ["preserve_order"] }
serde-saphyr = { git = "https://github.com/bourumir-wyngs/serde-saphyr" }
anyhow = { version = "1.0", features = ["std", "backtrace"] }
ureq = { version = "3.3" }
url = { version = "2.5.8", features = ["serde"] }
dirs = "6.0.0"
glob = "0.3.3"
dashu = { version = "0.4.1", features = [
  "num-order",
  "std",
  "serde",
  "num-traits",
] }
rpds = { "version" = "1.2.1", "features" = ["std", "serde", "rayon"] }
rayon = "1.12.0"
ropey = "1.6.1"
parking_lot = { version = "0.12.5", features = ["hardware-lock-elision"] }
gxhash = "3.5.0"

[dev-dependencies]
pretty_assertions = "1.4"
criterion = "0.5"

[[bench]]
name = "compute"
harness = false
